name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login Leetcode
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
      run: leetcode user -l $LEETCODE_USERNAME -p $LEETCODE_PASSWORD
    - name: Fetch Submissions
      run: leetcode submission -q -o json --all > submissions.json
    - name: Extract and Save Submissions
      run: |
        submissions=`cat submissions.json`
        for submission in $(echo $submissions | jq -r '.[]'); do
          pid=`echo $submission | jq -r '.problem_id'`
          code=`echo $submission | jq -r '.code'`
          filename=`leetcode show -q -g $pid | jq -r '.question.titleSlug'`.py
          echo $code > $filename
        done
    - name: Commit and Push
      run: |
        git add .
        git commit -m 'Sync LeetCode Submissions'
        git push
