name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install leetcode-cli
      run: npm install -g leetcode-cli

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install leetcode

    - name: Sync solutions
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
      run: |
        leetcode user -l $LEETCODE_USERNAME $LEETCODE_PASSWORD
        leetcode list -q "[easy,medium,hard]" -gx -o python > leetcode-problems.md
        git add leetcode-problems.md
        git commit -m "Sync LeetCode solutions"
