name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install leetcode-cli
    - name: Fetch and push solutions
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
      run: python sync-leetcode.py
